/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { PrimeFactorization } from "./PrimeFactorization";

export { PrimeFactorization__factory } from "./factories/PrimeFactorization__factory";
